name = "playground"
main = "./.output/server/index.mjs"
compatibility_date = "2022-09-10"
account_id = "9161f3bf7875fc457efb6c4fc392e289"

routes = [
    { pattern = "promptsroyale.com", custom_domain = true },
    { pattern = "www.promptsroyale.com", custom_domain = true }
]

[site]
bucket = ".output/public"

